package com.ynan._08.注解合成;

/**
 * @Author yuannan
 * @Date 2021/11/17 11:09
 */
@MyAnnotation(value = "xxxxx", condition = "condition---")
public class AnnoDemo {
//	THREE_IN_ONE_LICENSE
//	BUSINESS_LICENSE
//	TAX_REGISTRATION_CERTIFICATE
//	ORGANIZATION_CODE_CERTIFICATE
//	BANK_ACCOUNT_INFO
//	VAT_TAXPAYER_CERTIFICATE
//	FOOD_BUSINESS_LICENSE
//	PRODUCTION_LICENSE
//	QUALITY_SAFETY_LICENSE
//	AGENCY_AUTH_CERTIFICATE
//  SPECIAL_INDUSTRY_LICENSE
//	IMPORT_COMMODITY_LICENSE
//	GREEN_COMMODITY_LICENSE
//	PATENT_CERTIFICATE
//	COMMODITY_REGIST_CERTIFICATE
//	OTHER_CERTIFICATE
//	LAND_LEASE_CERTIFICATE
//	ORGANIC_PRODUCT_CERTIFICATE
//	SOIL_TEST_REPORT
//	IRRIGATION_WATER_TEST_REPORT
//	GOOD_AGR_PRACTICE_CERTIFICATE
//	REGIST_FOR_HKM_CERTIFICATE
//	GEO_INDICA_AGRICUL_PRODUCTS
//	PRODUCTION_OPERATION_LICENSE

//	VENDOR_NAME
//			VENDOR_ADDRESS
}
