package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_ASSIGNMENT_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u152/9742/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, September 14, 2017 2:31:42 AM PDT
*/

public interface ID_ASSIGNMENT_POLICY_ID
{

  /**
	 * The value representing ID_ASSIGNMENT_POLICY_ID.
	 */
  public static final int value = (int)(19L);
}
