package com.epichust.cxf.ws.sap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-06T23:05:25.721+08:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://sap.ws.cxf.epichust.com/", name = "ISapToMesService")
@XmlSeeAlso({ObjectFactory.class})
public interface ISapToMesService {

    @WebMethod
    @RequestWrapper(localName = "saveDeliveryData", targetNamespace = "http://sap.ws.cxf.epichust.com/", className = "com.epichust.cxf.ws.sap.SaveDeliveryData")
    @ResponseWrapper(localName = "saveDeliveryDataResponse", targetNamespace = "http://sap.ws.cxf.epichust.com/", className = "com.epichust.cxf.ws.sap.SaveDeliveryDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String saveDeliveryData(

            @WebParam(name = "arg0", targetNamespace = "")
                    java.util.List<DeliveryDataTO> arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.util.List<com.epichust.cxf.ws.sap.DeliveryDetailDataTO> arg1
    );
}
