package com.epichust.main.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-05-06T22:28:48.509+08:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://service.main.epichust.com/", name = "IWeatherService")
@XmlSeeAlso({ObjectFactory.class})
public interface IWeatherService {

    @WebMethod
    @RequestWrapper(localName = "sayBye", targetNamespace = "http://service.main.epichust.com/", className = "com.epichust.main.service.SayBye")
    @ResponseWrapper(localName = "sayByeResponse", targetNamespace = "http://service.main.epichust.com/", className = "com.epichust.main.service.SayByeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayBye(

        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0
    );

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.main.epichust.com/", className = "com.epichust.main.service.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.main.epichust.com/", className = "com.epichust.main.service.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
